#!/bin/sh
### BEGIN INIT INFO
# Provides:  UNATTENDED AUTO UPDATE && UPGRADE DEBIAN SYSTEM
# Required-Start:  $local_fs $network
# Required-Stop:  $local_fs
# Default-Start:  2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: UNATTENDED AUTO UPDATE && UPGRADE DEBIAN SYSTEM
# Description:  Unattended update and upgrade of debian system automatically
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# Create logs
touch /var/log/autopdate
# Check php7.2
#if [ $(dpkg-query -W -f='${Status}' php7.2 2>/dev/null | grep -c "ok installed") -eq 1 ]; then
#  apt-get -y install php7.2
#fi
# Check lxd
#if [ $(dpkg-query -W -f='${Status}' lxd 2>/dev/null | grep -c "ok installed") -eq 1 ]; then
#  apt-get -y install lxd
#fi
# Fix boken install, if any, then update
dpkg --configure -a && apt-get install --fix-broken && apt-get update
# Upgrade all available updates
apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y upgrade
# Clean up
apt-get -y autoremove && apt-get -y autoclean
# Reboot, if required (normally needed for kernel patches / updates
if [ -f /var/run/reboot-required ]; then
  shutdown -r now
fi
