#!/bin/sh
### BEGIN INIT INFO
# Provides:  UNATTENDED AUTO UPDATE && UPGRADE DEBIAN SYSTEM AT FIXED TIME
# Required-Start:  $local_fs $network
# Required-Stop:  $local_fs
# Default-Start:  2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: UNATTENDED AUTO UPDATE && UPGRADE DEBIAN SYSTEM AT FIXED TIME
# Description:  Unattended update and upgrade of debian system automatically at fixed time
### END INIT INFO
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
apt-get update && apt-get -y upgrade && apt-get -y autoremove && apt-get -y autoclean
if [ -f /var/run/reboot-required ]; then
	echo "30 3 * * * root shutdown -r;" >> /etc/cron.d/autopdate
	echo "@reboot root sleep 1 && rebuild=\$(sed -e :a -e '\$d;N;2,2ba' -e 'P;D' /etc/cron.d/autopdate); echo \"\$rebuild\" > /etc/cron.d/autopdate;" >> /etc/cron.d/autopdate
fi
