#!/bin/sh
### BEGIN INIT INFO
# Provides:  UNATTENDED AUTO UPDATE && UPGRADE DEBIAN SYSTEM
# Required-Start:  $local_fs $network
# Required-Stop:  $local_fs
# Default-Start:  2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: UNATTENDED AUTO UPDATE && UPGRADE DEBIAN SYSTEM
# Description:  Unattended update and upgrade of debian system automatically
### END INIT INFO
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# Sometimes I stucked at php update since I am using Ondrej Sury ppa for php, so this is a fix
if [ $(dpkg-query -W -f='${Status}' php7.2 2>/dev/null | grep -c "ok installed") -eq 1 ]; then
  apt- get -y install php7.2
fi
# LXD is available by default in Ubuntu 18 but update sometimes faced problem, so this is its fix
if [ $(dpkg-query -W -f='${Status}' lxd 2>/dev/null | grep -c "ok installed") -eq 1 ]; then
  apt- get -y install lxd
fi
# We need to configure the unfinished installation, if any
dpkg --configure -a && apt-get install --fix-broken
apt-get update && apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y upgrade
apt-get -y autoremove && apt-get -y autoclean
if [ -f /var/run/reboot-required ]; then
  shutdown -r now
fi
